"""02

Revision ID: 41acb96d7ea1
Revises: dc52291d48d2
Create Date: 2023-06-09 20:39:36.528257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41acb96d7ea1'
down_revision = 'dc52291d48d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###
